// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.

import { IAppConfig, IEnvironment } from './IEnvironment';
import { appBaseConfig, getEnvironmentBase } from './enviroment.base';
import { appCredentials } from './config.local';

const appConfig: IAppConfig = {
  ...appBaseConfig,
  credentials: appCredentials,
};

export const environment: IEnvironment = {
  ...getEnvironmentBase(appConfig),
};
