# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Conference' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CocoaLumberjack/Swift', '~> 3.5'
  pod 'VoxImplantSDK/CocoaLumberjackLogger', '2.34.0'
  pod 'SocketRocket'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
